### ISSUE TITLE
Initial data required? loadServerData: /home/jcb/river4data/data/prefsAndStats.json

### ISSUE THREAD

**Issue by jancbeck** [scripting/river4#8]
I'm setting up river4 on a CentOS 5 Linux server that runs node v0.12.2. fspath is set and river4data exists in the home directory. I'm running `node river4.js` and I get:

```
River4 v0.109 running on port 1337.

Running from the filesystem: /home/jcb/river4data/

loadServerData: /home/jcb/river4data/data/prefsAndStats.json
parseJson, error with S3 file: /home/jcb/river4data/data/prefsAndStats.json, Unexpected end of input
parseJson, error with S3 file: /home/jcb/river4data/data/feedsStats.json, Unexpected end of input
loadTodaysRiver: /home/jcb/river4data/data/calendar/2015/04/28.json

everyMinute: 20:19:29, 0 items on the task queue, 0 sockets open, undefined feeds.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1146:14)
    at listen (net.js:1172:10)
    at Server.listen (net.js:1257:5)
    at /var/www/virtual/jcb/html/river/river4.js:2836:39
    at /var/www/virtual/jcb/html/river/river4.js:1521:4
    at /var/www/virtual/jcb/html/river/river4.js:1431:3
    at fs.js:263:20
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Before that I had an error ENOENT error and it seemed that those files here were needed:
https://github.com/scripting/river4/blob/master/river4.js#L2815-L2823
So I created all those files manually but now I get parseJson errors because those files are empty of course.

What's going on here? The instructions say that only opml files in river4data/lists/ are required (I use the demo files). Shouldn't river4data/data be populated automatically by the server?

**Comment by scripting** [comment]
Sorry I'm just seeing this now.

The ENOENT message means it wasn't able to create the directory for its files, or able to create the file.

EADDRINUSE means some other app is using port 1337.

If you're still having the problem, I suggest posting to the River4 list. That's how we've been handling support issues.

**Comment by jancbeck** [comment]
Thanks, it was indeed the port which has been already in use.
